openapi: 3.0.0
info:
  title: Parliament REST API
  description: RESTful API for Candidates, Constituencies, Parliaments, Polls, Votes
    etc.
  version: v1
servers:
- url: https://virtserver.swaggerhub.com/Face-the-Facts/ParliamentAPI/v1
tags:
- name: Candidates
  description: Everything about candidates
- name: Parties
  description: Everything about parties
- name: Constituencies
  description: Everything about constituencies
- name: Poll
  description: everything about polls
paths:
  /candidates:
    get:
      tags:
      - Candidates
      description: Returns a list of candidates
      operationId: getCandidates
      parameters:
      - name: limit
        in: query
        description: Limits the number of items on a page
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: offset
        in: query
        description: Specifies the page number of the artists to be displayed
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: party
        in: query
        description: ID of the party to be filtered by
        required: false
        style: form
        explode: true
        schema:
          type: integer
      responses:
        "200":
          description: Successfully returned a list of candidates
          content:
            'application/json:':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Candidate'
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400'
    post:
      tags:
      - Candidates
      description: Create a new Candidate
      operationId: postCandidate
      requestBody:
        description: Optional description in *Markdown*
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Candidate'
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201'
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400'
        "404":
          description: 404 Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400'
  /candidates/{id}:
    get:
      tags:
      - Candidates
      description: Returns a candidate by ID
      operationId: getCandidate
      parameters:
      - name: id
        in: path
        description: The ID of the candidate to return
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: OK
          content:
            'application/json:':
              schema:
                $ref: '#/components/schemas/Candidate'
          links:
            GetCandidateParty:
              operationId: getParty
              parameters:
                partyId: $response.body#/party
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400'
        "404":
          description: 404 Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400'
  /parties:
    get:
      tags:
      - Parties
      description: Returns a collection of Parties
      parameters:
      - name: partyId
        in: query
        description: The ID of the Political Party to return
        required: false
        style: form
        explode: true
        schema:
          type: integer
      responses:
        "200":
          description: OK
          content:
            'application/json:':
              schema:
                $ref: '#/components/schemas/Party'
    post:
      tags:
      - Parties
      description: Create a new Candidate
      operationId: postParty
      requestBody:
        description: Political party to be added
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Party'
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201'
    head:
      tags:
      - Parties
      responses:
        "200":
          description: OK
  /parties/{id}:
    get:
      tags:
      - Parties
      description: Returns a Political Party by ID
      parameters:
      - name: id
        in: path
        description: The ID of the Political Party to return
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: OK
          content:
            'application/json:':
              schema:
                $ref: '#/components/schemas/Party'
          links:
            GetPartyMembers:
              operationId: GetCandidatesByParty
              parameters:
                politicalParty: $response.body#/id
    put:
      tags:
      - Parties
      description: Replace a Party
      operationId: putParty
      parameters:
      - name: id
        in: path
        description: The ID of the Political Party to return
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      requestBody:
        description: Optional description in *Markdown*
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Party'
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201'
    delete:
      tags:
      - Parties
      description: Delete a Party
      operationId: deleteParty
      parameters:
      - name: id
        in: path
        description: The ID of the Political Party to return
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201'
    patch:
      tags:
      - Parties
      description: Partially update a Party
      operationId: patchParty
      parameters:
      - name: id
        in: path
        description: The ID of the Political Party to return
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      requestBody:
        description: Optional description in *Markdown*
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Party'
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201'
components:
  schemas:
    Candidate:
      required:
      - candidateId
      type: object
      properties:
        id:
          type: integer
          readOnly: true
          example: 1
        name:
          type: string
          example: Philipp Amthor
        image:
          $ref: '#/components/schemas/Candidate_image'
        party:
          type: integer
          example: 1
      description: Electoral Candidate for political office
    Constituency:
      description: Electoral Constituency
    Party:
      required:
      - id
      type: object
      properties:
        id:
          type: integer
          readOnly: true
          example: 1
        name:
          type: string
          example: CDU/CSU
      description: Political Party
    Poll:
      properties:
        id:
          type: integer
          readOnly: true
        label:
          type: string
        result:
          $ref: '#/components/schemas/Poll_result'
      description: Parliamentary Poll
    Vote:
      properties:
        id:
          type: integer
          readOnly: true
        candidate:
          type: integer
        poll:
          type: integer
      description: Vote on Parliamentary Poll
    inline_response_400:
      type: object
      properties:
        message:
          type: string
    inline_response_201:
      type: object
      properties:
        id:
          type: integer
    Candidate_image_bbox:
      type: object
      properties:
        minX:
          type: number
          format: double
          example: 0
        maxX:
          type: number
          format: double
          example: 2746
        minY:
          type: number
          format: double
          example: 0
        maxY:
          type: number
          format: double
          example: 2746
    Candidate_image:
      type: object
      properties:
        src:
          type: string
          example: https://commons.wikimedia.org/wiki/File:Philipp_Amthor.jpg#/media/File:Philipp_Amthor.jpg
        bbox:
          $ref: '#/components/schemas/Candidate_image_bbox'
    Poll_result:
      type: object
      properties:
        "yes":
          type: integer
        "no":
          type: integer
        abstain:
          type: integer
        no_vote:
          type: integer
  responses:
    "400Error":
      description: Invalid request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_response_400'
    "404Error":
      description: 404 Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_response_400'
    "201Created":
      description: Created
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_response_201'
  parameters:
    PageLimit:
      name: limit
      in: query
      description: Limits the number of items on a page
      required: false
      style: form
      explode: true
      schema:
        type: integer
    PageNumber:
      name: offset
      in: query
      description: Specifies the page number of the artists to be displayed
      required: false
      style: form
      explode: true
      schema:
        type: integer
    Candidate:
      name: candidate
      in: query
      description: ID of the candidate to be filtered by
      required: false
      style: form
      explode: true
      schema:
        type: integer
    PartyId:
      name: party
      in: query
      description: ID of the party to be filtered by
      required: false
      style: form
      explode: true
      schema:
        type: integer
