openapi: 3.0.0
info:
  title: Face the Facts API
  description: Face the Facts API
  contact:
    email: fabi@facethefacts.app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/Face-the-Facts/REST-API/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: Candidates
  description: Everything about candidates
- name: Parties
  description: Everything about parties
- name: Constituencies
  description: Everything about constituencies
- name: Poll
  description: everything about polls
paths:
  /candidates:
    $ref: './paths/candidates.yaml'
  /candidates/{id}:
    $ref: './paths/candidate.yaml'
  /elections:
    $ref: './paths/elections.yaml'
  /elections/{id}:
    $ref: './paths/election.yaml'
  /parties:
    $ref: './paths/parties.yaml'
  /parties/{id}:
    $ref: './paths/party.yaml'
components:
  parameters:
    $ref: "./parameters/_index.yaml"
  schemas:
    $ref: "./schemas/_index.yaml"
  responses:
    $ref: "./responses/_index.yaml"
  # examples:
  #   $ref: "./examples/_index.yaml"
  # callbacks:
  #   $ref: "./callbacks/_index.yaml"
  # headers:
  #   $ref: "./headers/_index.yaml"
  # links:
  #   $ref: "./links/_index.yaml"
  # requestBodies:
  #   $ref: "./requestBodies/_index.yaml"
  # securitySchemes:
  #   $ref: "./securitySchemes/_index.yaml"