// tslint:disable
/**
 * Parliament REST API
 * RESTful API for Candidates, Constituencies, Parliaments, Polls, Votes etc.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

export * from "./api";
export * from "./configuration";
